spring.datasource.url=jdbc:h2:file:./data/demo-db;CACHE_SIZE=262144
spring.datasource.driver-class-name=org.h2.Driver
spring.main.log-startup-info=false

spring.datasource.hikari.maximum-pool-size=4
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=1000

spring.sql.init.schema-locations=classpath:db/schema.sql

spring.sql.init.mode=always

spring.servlet.multipart.max-file-size=10MB