-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
--  Lorebook system
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

CREATE TABLE IF NOT EXISTS OUTLET
(
    id     INT          NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    outlet VARCHAR(255) NOT NULL UNIQUE
);


CREATE TABLE IF NOT EXISTS LOREBOOKS
(
    id                INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created           TIMESTAMP             DEFAULT CURRENT_TIMESTAMP NOT NULL,
    name              VARCHAR(255) NOT NULL,
    default_outlet_id INT REFERENCES OUTLET (id),
    next_entry_id     INT          NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS ENTRY
(
    lorebook_id               INT  NOT NULL,
    entry_id                  INT  NOT NULL,
    name                      VARCHAR(255),
    enabled                   bool NOT NULL DEFAULT TRUE,
    content                   TEXT,

    -- Injection requirements
    probability               smallint      default 100,
    is_custom_outlet          BOOL NOT NULL DEFAULT FALSE,
    outlet                    INT REFERENCES OUTLET (id),
    delay                     INT  NOT NULL default 0,
    cooldown                  INT  NOT NULL default 0,
    stick_through             INT  NOT NULL default 0,

    -- Injection options
    injection_order           smallint      default 100,

    -- Activation strategy
    strategy                  smallint      default 0,
    embed_text                TEXT,
    prevent_further_recursion bool NOT NULL default false,
    non_recursable            bool NOT NULL default false,
    delay_until_recursion     bool NOT NULL default false,

    scan_depth                smallint      default null,


    PRIMARY KEY (lorebook_id, entry_id),
    FOREIGN KEY (lorebook_id) REFERENCES LOREBOOKS (id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS KEYWORD
(
    id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    is_regex BOOL                NOT NULL DEFAULT FALSE,
    keyword  VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS ENTRY_KEYWORDS
(
    lorebook_id INT NOT NULL REFERENCES LOREBOOKS (id),
    entry_id    INT NOT NULL,
    keyword_id  INT NOT NULL REFERENCES KEYWORD (id),

    PRIMARY KEY (lorebook_id, entry_id, keyword_id),
    FOREIGN KEY (lorebook_id, entry_id) REFERENCES ENTRY (lorebook_id, entry_id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS entriesByKeywords ON ENTRY_KEYWORDS (keyword_id);

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- TAGS
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CREATE TABLE IF NOT EXISTS TAGS
(
    id    INT                 NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name  VARCHAR(255) UNIQUE NOT NULL,
    color CHAR(7)             NOT NULL DEFAULT '#000000'
);

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Generations
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CREATE TABLE IF NOT EXISTS API_HOSTS
(
    id       INT          NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    host_url varchar(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS API_KEYS
(
    name                varchar(255),
    key_id              INT             NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    host_id             INT             NOT NULL REFERENCES API_HOSTS (id),

    api_key_ciphertext  VARBINARY(2048) NOT NULL,
    api_key_nonce       VARBINARY(12)   NOT NULL,
    api_key_key_version INT             NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS LLM_CONNECTION
(
    id         INT                 NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    host_id    smallint REFERENCES API_HOSTS (id),

    name       varchar(255) UNIQUE NOT NULL,

    model      VARCHAR(255)        NOT NULL DEFAULT '',
    max_tokens INT                          DEFAULT 4192,

    CONSTRAINT chk_max_tokens_non_negative CHECK (max_tokens > 0)
);

CREATE TABLE IF NOT EXISTS PROMPT_TEMPLATE
(
    id                 smallint     NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    connection_id      INT REFERENCES LLM_CONNECTION (id),
    name               VARCHAR(300) NOT NULL UNIQUE,

    --Generation config
    max_tokens         INT          NOT NULL DEFAULT 8192,
    streaming          bool         NOT NULL default false,

    --Gen params
    temperature        float4       NOT NULL DEFAULT 1,
    top_p              float4       NOT NULL default 0.95,
    frequency_penalty  float4       NOT NULL default 0,
    presence_penalty   float4       NOT NULL default 0,
    repetition_penalty float4       NOT NULL default 0,
    top_k              int          NOT NULL default 0,

    -- Reasoning
    exclude_reasoning  bool         NOT NULL default true,
    reasoning_effort   smallint     NOT NULL,

    next_section_id    smallint     NOT NULL default 0,

    CONSTRAINT chk_prompt_template_max_tokens
        CHECK (max_tokens > 0),

    CONSTRAINT chk_prompt_template_temperature
        CHECK (temperature >= 0 AND temperature <= 2),

    CONSTRAINT chk_prompt_template_top_p
        CHECK (top_p >= 0 AND top_p <= 1),

    CONSTRAINT chk_prompt_template_frequency_penalty
        CHECK (frequency_penalty >= -2 AND frequency_penalty <= 2),

    CONSTRAINT chk_prompt_template_presence_penalty
        CHECK (presence_penalty >= -2 AND presence_penalty <= 2),

    CONSTRAINT chk_prompt_template_repetition_penalty
        CHECK (repetition_penalty >= 0 AND repetition_penalty <= 2),

    CONSTRAINT chk_prompt_template_top_k
        CHECK (top_k >= 0),

    CONSTRAINT chk_prompt_template_reasoning_effort
        CHECK (reasoning_effort IS NULL OR reasoning_effort IN (0, 1, 2, 3, 4, 5)),

    CONSTRAINT chk_prompt_template_next_section_id
        CHECK (next_section_id >= 0)
);

CREATE TABLE IF NOT EXISTS PROMPT_SECTION
(
    prompt_id  smallint     NOT NULL REFERENCES PROMPT_TEMPLATE (id),
    section_id SMALLINT     NOT NULL,
    name       VARCHAR(128) NOT NULL UNIQUE,
    position   SMALLINT     NOT NULL UNIQUE,

    active     boolean      NOT NULL default true,
    role       VARCHAR(9)   NOT NULL DEFAULT 'user',
    content    TEXT         NOT NULL DEFAULT ''
);

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
--  Extensions
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CREATE TABLE IF NOT EXISTS EXTENSION
(
    id         VARCHAR(255)      NOT NULL PRIMARY KEY,
    config     JSON,
    is_enabled BOOL DEFAULT true NOT NULL,
);
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
--  Injections
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CREATE TABLE IF NOT EXISTS ENTRY_OUTLET
(
    lorebook_id INT NOT NULL,
    entry_id    INT NOT NULL,
    outlet_id   INT NOT NULL,

    FOREIGN KEY (lorebook_id, entry_id) REFERENCES ENTRY (lorebook_id, entry_id)
);

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
--  Entities
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CREATE TABLE IF NOT EXISTS CHARACTERS
(
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    created         TIMESTAMP DEFAULT CURRENT_TIMESTAMP              NOT NULL,
    name            VARCHAR(255)                                     NOT NULL UNIQUE,

    description     TEXT      DEFAULT ''                             NOT NULL,
    is_archetype    BOOL      DEFAULT False                          NOT NULL, --This will be worked on later versions.
    can_be_user     BOOL      DEFAULT False                          NOT NULL,
    welcome_message TEXT      DEFAULT ' '                            NOT NULL,

    --Entries
    lorebook_id     INT                                              NOT NULL REFERENCES LOREBOOKS (id)
);
CREATE TABLE IF NOT EXISTS WORLDS
(
    id               INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             VARCHAR(255) UNIQUE NOT NULL,
    description      TEXT DEFAULT ''     NOT NULL,
    next_location_id INT  DEFAULT 0      NOT NULL,

    lorebook_id      INT                 NOT NULL,
    FOREIGN KEY (lorebook_id) REFERENCES LOREBOOKS (id)
);
CREATE TABLE IF NOT EXISTS LOCATIONS
(
    --PK
    id          INT             NOT NULL,
    world_id    INT             NOT NULL,

    --Location info
    name        VARCHAR(255)    NOT NULL,
    description TEXT DEFAULT '' NOT NULL,
    lorebook_id INT             NOT NULL REFERENCES LOREBOOKS (id),

    PRIMARY KEY (world_id, id),
    FOREIGN KEY (world_id) REFERENCES WORLDS (id) ON DELETE CASCADE,
    UNIQUE (world_id, name)
);

CREATE TABLE IF NOT EXISTS starting_locations
(
    character_id INT     NOT NULL,
    world_id     INT     NOT NULL,
    location_id  INT     NOT NULL,

    is_static    BOOLEAN NOT NULL DEFAULT FALSE,

    reason_why   TEXT,                    --Why the character is there, not the reason why its static
    ttl          INT              DEFAULT 0,

    PRIMARY KEY (character_id, world_id), --At most one starting location per character per world. Characters are NOT archetypes
    FOREIGN KEY (character_id) REFERENCES characters (id) ON DELETE CASCADE,
    FOREIGN KEY (world_id, location_id) REFERENCES LOCATIONS (world_id, id) ON DELETE CASCADE,
    FOREIGN KEY (world_id) REFERENCES WORLDS (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS location_neighbors
(
    world_id        INT NOT NULL,
    location1_id    INT NOT NULL,
    location2_id    INT NOT NULL,

    travelCost      INT NOT NULL DEFAULT 0,
    edgeDescription TEXT,

    PRIMARY KEY (world_id, location1_id, location2_id),
    FOREIGN KEY (world_id, location1_id) REFERENCES LOCATIONS (world_id, id) ON DELETE CASCADE,
    FOREIGN KEY (world_id, location2_id) REFERENCES LOCATIONS (world_id, id) ON DELETE CASCADE,
    CONSTRAINT chk_duplicates CHECK (location1_id <> location2_id) --We disallow self edges
);


-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Entities tags
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CREATE TABLE IF NOT EXISTS CHARACTER_TAGS
(
    tag_id  INT NOT NULL,
    char_id INT NOT NULL,

    PRIMARY KEY (tag_id, char_id),
    FOREIGN KEY (tag_id) REFERENCES TAGS (id) ON DELETE CASCADE,
    FOREIGN KEY (char_id) REFERENCES CHARACTERS (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS LOCATION_TAGS
(
    tag_id      INT NOT NULL,
    world_id    INT NOT NULL,
    location_id INT NOT NULL,

    PRIMARY KEY (tag_id, world_id, location_id),
    FOREIGN KEY (world_id, location_id) REFERENCES LOCATIONS (world_id, id) ON DELETE CASCADE,
    FOREIGN KEY (tag_id) REFERENCES TAGS (id)
);

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Entry condition tree
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- CREATE TABLE IF NOT EXISTS ENTRY_CONDITION_GROUP
-- (
--     id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--
--     lorebook_id     INT      NOT NULL,
--     entry_id        INT      NOT NULL,
--
--     parent_group_id INT,
--
--     operator        SMALLINT NOT NULL DEFAULT 0,     -- AND / OR
--     negated         BOOLEAN  NOT NULL DEFAULT FALSE, -- Invert conditional
--
--     FOREIGN KEY (lorebook_id, entry_id)
--         REFERENCES ENTRY (lorebook_id, entry_id)
--         ON DELETE CASCADE,
--
--     FOREIGN KEY (parent_group_id)
--         REFERENCES ENTRY_CONDITION_GROUP (id)
--         ON DELETE CASCADE
-- );
--
-- CREATE TABLE IF NOT EXISTS ENTRY_CONDITION
-- (
--     id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--
--     group_id        INT      NOT NULL,
--
--     condition_type  SMALLINT NOT NULL, -- IN_LOCATION / CHARACTER_PRESENT / TAG_PRESENT / ENTITY_HAS_TAG
--     target_type     SMALLINT NOT NULL, -- NONE, CHARACTER, LOCATION, TAG
--     target_id       INT,
--     target_world_id INT,
--
--     negated         BOOLEAN  NOT NULL DEFAULT FALSE,
--
--     FOREIGN KEY (group_id)
--         REFERENCES ENTRY_CONDITION_GROUP (id)
--         ON DELETE CASCADE
-- );

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Dynamic info (actual messages)
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CREATE TABLE IF NOT EXISTS sessions
(
    id              INT          NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255) NOT NULL,

    world_id        INT          NOT NULL REFERENCES WORLDS (id) ON DELETE CASCADE,
    main_prompt     INT REFERENCES PROMPT_TEMPLATE (id),
    user_persona_id INT          NOT NULL REFERENCES CHARACTERS (id) ON DELETE CASCADE, -- User character ID
    current_tick    INT          NOT NULL DEFAULT 0                                     -- Incrementing for handing down ids to messages
);


CREATE TABLE IF NOT EXISTS messages
(
    session_id      INT        NOT NULL REFERENCES SESSIONS (id) ON DELETE CASCADE,
    tick_num        INT        NOT NULL,

    role            varchar(9) NOT NULL CHECK (role = 'user' OR role = 'assistant'),
    request_json    TEXT,                                       -- Stored, but it could also just be regen. Should only be there for assistant msgs
    content         TEXT,                                       -- Always derived

    time            INT        NOT NULL,
    world_id        INT        NOT NULL REFERENCES WORLDS (id), -- Derived
    location_id     INT        NOT NULL,                        -- Derived

    active_response SMALLINT   NOT NULL DEFAULT 0,              -- ID of the response that's currently active
    response_num    SMALLINT   NOT NULL DEFAULT 0,              -- Response num counter to assign keys.

    PRIMARY KEY (session_id, tick_num),
    FOREIGN KEY (location_id, world_id) REFERENCES LOCATIONS (id, world_id),
    CONSTRAINT request_json_only_for_generated_messages CHECK (request_json IS NULL OR role = 'assistant')
);

CREATE TABLE IF NOT EXISTS extras
(
    session_id   INT  NOT NULL REFERENCES SESSIONS (id) ON DELETE CASCADE,
    tick_num     INT  NOT NULL,
    extension_id VARCHAR(255) REFERENCES EXTENSION (id),

    position     int  NOT NULL,
    content      TEXT NOT NULL,

    PRIMARY KEY (session_id, tick_num, extension_id),
    FOREIGN KEY (session_id, tick_num) references MESSAGES (session_id, tick_num)
);

CREATE TABLE IF NOT EXISTS responses
(
    session_id       INT      NOT NULL REFERENCES SESSIONS (id) ON DELETE CASCADE,
    tick_num         INT      NOT NULL,
    response_num     SMALLINT NOT NULL,

    location_id      INT      NOT NULL,
    world_id         INT      NOT NULL REFERENCES WORLDS (id),

    advances_time_by INT      NOT NULL,
    content          TEXT     NOT NULL,

    PRIMARY KEY (session_id, tick_num, response_num),
    FOREIGN KEY (location_id, world_id) REFERENCES LOCATIONS (id, world_id) ON DELETE CASCADE,

    FOREIGN KEY (session_id, tick_num)
        REFERENCES messages (session_id, tick_num)
        ON DELETE CASCADE
);

-- MOVEMENT TRACKER ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CREATE TABLE IF NOT EXISTS response_location_changes
(
    session_id   INT      NOT NULL,
    tick_num     INT      NOT NULL,
    response_num SMALLINT NOT NULL,

    character_id INT      NOT NULL REFERENCES characters (id),

    -- Location after applying this response
    world_id     INT      NOT NULL,
    location_id  INT      NOT NULL,

    PRIMARY KEY (
                 session_id,
                 tick_num,
                 response_num,
                 character_id
        ),

    FOREIGN KEY (
                 session_id,
                 tick_num,
                 response_num
        )
        REFERENCES responses (
                              session_id,
                              tick_num,
                              response_num
            )
        ON DELETE CASCADE,

    FOREIGN KEY (location_id, world_id)
        REFERENCES locations (id, world_id)
);

CREATE TABLE IF NOT EXISTS MOVEMENTS
(
    session_id           INT NOT NULL REFERENCES SESSIONS (id) ON DELETE CASCADE,
    at_tick              INT NOT NULL,

    character_id         INT NOT NULL REFERENCES CHARACTERS (id),

    -- Location before this particular response moved the character.
    world_id             INT NOT NULL REFERENCES WORLDS (id),
    previous_location_id INT NOT NULL,

    PRIMARY KEY (session_id, at_tick, character_id),
    FOREIGN KEY (previous_location_id, world_id) references LOCATIONS (id, world_id),
    FOREIGN KEY (session_id, at_tick) references MESSAGES (session_id, tick_num) ON DELETE CASCADE
);

-- CACHE TABLE, current linear history locations (only accounts for active responses)
CREATE TABLE IF NOT EXISTS CURRENT_LOCATIONS
(
    session_id   INT NOT NULL REFERENCES SESSIONS (id) ON DELETE CASCADE,
    tick_num     INT NOT NULL,                            -- When did this guy reach this location? (In message tick). Isn't necessarily the last message tick.

    character_id INT NOT NULL REFERENCES CHARACTERS (id), -- who

    world_id     INT NOT NULL REFERENCES WORLDS (id),     -- where
    location_id  INT NOT NULL,

    PRIMARY KEY (session_id, character_id),
    FOREIGN KEY (location_id, world_id) REFERENCES LOCATIONS (id, world_id),
    FOREIGN KEY (session_id, tick_num) REFERENCES MESSAGES (session_id, tick_num) ON DELETE CASCADE
);