-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
--  Lorebook system
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CREATE TABLE LOREBOOKS
(
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created       TIMESTAMP             DEFAULT CURRENT_TIMESTAMP NOT NULL,
    name          VARCHAR(255) NOT NULL,

    next_entry_id INT          NOT NULL DEFAULT 0
);

CREATE TABLE ENTRY
(
    lorebook_id               INT  NOT NULL,
    entry_id                  INT  NOT NULL,
    name                      VARCHAR(255),

    content                   TEXT,

    -- Injection requirements
    probability               smallint      default 100,
    outlet                    VARCHAR(255),
    delay                     INT  NOT NULL default 0,
    cooldown                  INT  NOT NULL default 0,
    stick_through             INT  NOT NULL default 0,

    -- Injection options
    injection_order           smallint      default 100,

    -- Activation strategy
    strategy                  smallint      default 0,
    embed_text                TEXT,
    prevent_further_recursion bool NOT NULL default false,
    non_recursable            bool NOT NULL default false,
    delay_until_recursion     bool NOT NULL default false,

    scan_depth                smallint      default null,


    PRIMARY KEY (lorebook_id, entry_id),
    FOREIGN KEY (lorebook_id) REFERENCES LOREBOOKS (id) ON DELETE CASCADE
);

CREATE TABLE KEYWORD
(
    id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    is_regex BOOL NOT NULL DEFAULT FALSE,
    keyword  VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE ENTRY_KEYWORDS
(
    lorebook_id INT NOT NULL,
    entry_id    INT NOT NULL,
    keyword_id  INT NOT NULL,

    PRIMARY KEY (lorebook_id, entry_id, keyword_id),
    FOREIGN KEY (lorebook_id, entry_id) REFERENCES ENTRY (lorebook_id, entry_id) ON DELETE CASCADE,
    FOREIGN KEY (keyword_id) REFERENCES KEYWORD (id)
);

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- TAGS
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CREATE TABLE TAGS
(
    id    INT                 NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name  VARCHAR(255) UNIQUE NOT NULL,
    color CHAR(7)             NOT NULL DEFAULT '#000000'
);

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Generations
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

CREATE TABLE CONNECTION
(
    id      INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    host    VARCHAR(300),
    API_KEY VARBINARY(64),
    model   VARCHAR(255),
    type    VARCHAR(255)
);

CREATE TABLE COMFY_UI
(
    id        INT NOT NULL,
    host      VARCHAR(300),

    --Actual params
    workflow  JSON,
    steps     smallint     default 20,
    sampler   VARCHAR(255) default 'euler_ancestral',
    scheduler VARCHAR(255) default 'normal',
    CFG       smallint     default 6,

    FOREIGN KEY (id) REFERENCES CONNECTION (id)
);

CREATE TABLE PROMPT_TEMPLATE
(
    id                INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    connection_id     INT,
    name              VARCHAR(300),

    --Generation config
    max_tokens        INT    DEFAULT 8192,
    temperature       float4 DEFAULT 1,
    frequency_penalty float4 default 0,
    presence_penalty  float4 default 0,
    top_p             float4 default 0.95,

    -- Backend config
    streaming         bool   default false,
    request_reasoning bool   default true,

    -- Prompt
    raw_content       BLOB,

    FOREIGN KEY (connection_id) REFERENCES CONNECTION (id)
);

CREATE TABLE MAIN_PROMPT
(
    id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FOREIGN KEY (id) REFERENCES PROMPT_TEMPLATE (id)
);

CREATE TABLE EXTENSION_PROMPT
(
    id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FOREIGN KEY (id) REFERENCES PROMPT_TEMPLATE (id)
);


-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
--  Extensions
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CREATE TABLE EXTENSION
(
    id   INT          NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
--  Injections
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CREATE TABLE OUTLET
(
    id      INT          NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    keyword VARCHAR(255) NOT NULL
);

CREATE TABLE ENTRY_OUTLET
(
    lorebook_id INT NOT NULL,
    entry_id    INT NOT NULL,
    outlet_id   INT NOT NULL,

    FOREIGN KEY (lorebook_id, entry_id) REFERENCES ENTRY (lorebook_id, entry_id)
);

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
--  Entities
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CREATE TABLE CHARACTERS
(
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    name        VARCHAR(255)                        NOT NULL UNIQUE,

    --Entries
    lorebook_id INT                                 NOT NULL,

    FOREIGN KEY (lorebook_id) REFERENCES LOREBOOKS (id)
);
CREATE TABLE WORLDS
(
    id               INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             VARCHAR(255) NOT NULL UNIQUE,
    next_location_id INT          NOT NULL DEFAULT 0,

    lorebook_id      INT          NOT NULL,
    FOREIGN KEY (lorebook_id) REFERENCES LOREBOOKS (id)
);
CREATE TABLE LOCATIONS
(
    --PK
    id          INT          NOT NULL,
    world_id    INT          NOT NULL,

    --Location info
    name        VARCHAR(255) NOT NULL,
    description BLOB, --Always active when inside location
    lorebook_id INT,  --For other things

    PRIMARY KEY (world_id, id),
    FOREIGN KEY (world_id) REFERENCES WORLDS (id) ON DELETE CASCADE,
    FOREIGN KEY (lorebook_id) REFERENCES LOREBOOKS (id),
    UNIQUE (world_id, name)
);

CREATE TABLE starting_locations
(
    character_id INT     NOT NULL,
    world_id     INT     NOT NULL,
    location_id  INT     NOT NULL,

    is_static    BOOLEAN NOT NULL DEFAULT FALSE,

    reason_why   TEXT,                    --Why the character is there, not the reason why its static
    ttl          INT              DEFAULT 0,

    PRIMARY KEY (character_id, world_id), --At most one starting location per character per world
    FOREIGN KEY (character_id) REFERENCES characters (id) ON DELETE CASCADE,
    FOREIGN KEY (world_id, location_id) REFERENCES LOCATIONS (world_id, id) ON DELETE CASCADE
);

CREATE TABLE location_neighbors
(
    world_id        INT NOT NULL,
    location1_id    INT NOT NULL,
    location2_id    INT NOT NULL,

    travelCost      INT NOT NULL DEFAULT 0,
    edgeDescription TEXT,

    PRIMARY KEY (world_id, location1_id, location2_id),
    FOREIGN KEY (world_id, location1_id) REFERENCES LOCATIONS (world_id, id) ON DELETE CASCADE,
    FOREIGN KEY (world_id, location2_id) REFERENCES LOCATIONS (world_id, id) ON DELETE CASCADE
);


-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Entities tags
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CREATE TABLE CHARACTER_TAGS
(
    tag_id  INT NOT NULL,
    char_id INT NOT NULL,

    PRIMARY KEY (tag_id, char_id),
    FOREIGN KEY (tag_id) REFERENCES TAGS (id) ON DELETE CASCADE,
    FOREIGN KEY (char_id) REFERENCES CHARACTERS (id) ON DELETE CASCADE
);

CREATE TABLE LOCATION_TAGS
(
    tag_id      INT NOT NULL,
    world_id    INT NOT NULL,
    location_id INT NOT NULL,

    PRIMARY KEY (tag_id, world_id, location_id),
    FOREIGN KEY (world_id, location_id) REFERENCES LOCATIONS (world_id, id) ON DELETE CASCADE,
    FOREIGN KEY (tag_id) REFERENCES TAGS (id)
);

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Entry condition tree
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CREATE TABLE ENTRY_CONDITION_GROUP
(
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    lorebook_id     INT      NOT NULL,
    entry_id        INT      NOT NULL,

    parent_group_id INT,

    operator        SMALLINT NOT NULL DEFAULT 0, -- AND / OR
    negated         BOOLEAN  NOT NULL DEFAULT FALSE, -- Invert conditional

    FOREIGN KEY (lorebook_id, entry_id)
        REFERENCES ENTRY (lorebook_id, entry_id)
        ON DELETE CASCADE,

    FOREIGN KEY (parent_group_id)
        REFERENCES ENTRY_CONDITION_GROUP (id)
        ON DELETE CASCADE
);

CREATE TABLE ENTRY_CONDITION
(
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    group_id        INT      NOT NULL,

    condition_type  SMALLINT NOT NULL, -- IN_LOCATION / CHARACTER_PRESENT / TAG_PRESENT / ENTITY_HAS_TAG
    target_type     SMALLINT NOT NULL, -- NONE, CHARACTER, LOCATION, TAG
    target_id       INT,
    target_world_id INT,

    negated         BOOLEAN  NOT NULL DEFAULT FALSE,

    FOREIGN KEY (group_id)
        REFERENCES ENTRY_CONDITION_GROUP (id)
        ON DELETE CASCADE
);

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Dynamic info (actual messages)
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CREATE TABLE sessions
(
    id              INT NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    world_id        INT NOT NULL,
    start_time      VARCHAR(300),


    user_persona_id INT NOT NULL,           -- User character ID
    current_tick    INT NOT NULL DEFAULT 0, -- Incrementing for handing down ids to messages

    FOREIGN KEY (world_id) REFERENCES worlds (id) ON DELETE CASCADE,
    FOREIGN KEY (user_persona_id) REFERENCES characters (id) ON DELETE CASCADE
);

CREATE TABLE messages
(
    session_id       INT  NOT NULL,
    tick_num         INT  NOT NULL,

    location_id      INT  NOT NULL,

    advances_time_by INT  NOT NULL,
    user_generated   bool NOT NULL,
    content          TEXT NOT NULL,

    PRIMARY KEY (session_id, tick_num),

    FOREIGN KEY (session_id)
        REFERENCES sessions (id)
        ON DELETE CASCADE
);
-- MESSAGE TYPES ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CREATE TABLE LLM_GEN
(
    session_id      INT      NOT NULL,
    tick_num        INT      NOT NULL,
    prompt          TEXT     NOT NULL,           -- Stored, but it could also just be regen (its deterministic)

    -- RESPONSES
    active_response SMALLINT NOT NULL DEFAULT 0, -- ID of the response that's currently active
    response_num    SMALLINT NOT NULL DEFAULT 0, -- Response num is the way I have to assign keys

    PRIMARY KEY (session_id, tick_num),
    FOREIGN KEY (session_id, tick_num) REFERENCES messages (session_id, tick_num) ON DELETE CASCADE
);

CREATE TABLE responses
(
    session_id   INT      NOT NULL,
    tick_num     INT      NOT NULL,
    response_num SMALLINT NOT NULL,
    content      TEXT     NOT NULL,

    PRIMARY KEY (session_id, tick_num, response_num),

    FOREIGN KEY (session_id, tick_num)
        REFERENCES messages (session_id, tick_num)
        ON DELETE CASCADE
);

