spring.datasource.url=jdbc:h2:file:./data/demo-db
spring.datasource.driver-class-name=org.h2.Driver
spring.main.log-startup-info=false

spring.sql.init.schema-locations=classpath:db/schema.sql
spring.sql.init.mode=embedded

spring.servlet.multipart.max-file-size=10MB