// src/services/apiClient.ts

import { setGlobalError } from "@/core/GlobalError";
import { ApiRequestError } from "@/core/ApiRequestError";

interface CsrfState {
    headerName: string;
    token: string;
}

export enum Severity {
    EXPECTED = "EXPECTED",
    USER = "USER",
    SYSTEM = "SYSTEM",
}

export type ErrorResponse = {
    status: number;
    type: string;
    message: string;
    path: string;
    severity: Severity;
};

export interface FetchApiInit extends RequestInit {
    /**
     * Set to false when the caller handles the failure itself and no global
     * notification should be displayed.
     */
    showGlobalError?: boolean;
}

const SAFE_METHODS = new Set([
    "GET",
    "HEAD",
    "OPTIONS",
    "TRACE",
]);

let csrfState: CsrfState | null = null;

/**
 * Prevents simultaneous unsafe requests from issuing multiple CSRF-token
 * requests during initialization.
 */
let csrfLoadPromise: Promise<CsrfState> | null = null;

export function logError(
    prefix: string,
    error: ErrorResponse | null | undefined,
): void {
    if (error == null) {
        console.error(
            `Empty error response while handling error. Prefix: ${prefix}`,
        );
        return;
    }

    const content = `${prefix}${error.message}`;

    switch (error.severity) {
        case Severity.EXPECTED:
            console.trace(content, error);
            break;

        case Severity.USER:
            console.info(content, error);
            break;

        case Severity.SYSTEM:
            console.error(content, error);
            break;

        default: {
            const exhaustiveCheck: never = error.severity;
            console.error(
                `Unknown error severity: ${String(exhaustiveCheck)}`,
                error,
            );
        }
    }
}

function isRecord(
    value: unknown,
): value is Record<string, unknown> {
    return typeof value === "object" && value !== null;
}

function readString(
    source: Record<string, unknown>,
    key: string,
): string | undefined {
    const value = source[key];

    return typeof value === "string" && value.length > 0
        ? value
        : undefined;
}

function readNumber(
    source: Record<string, unknown>,
    key: string,
): number | undefined {
    const value = source[key];

    return typeof value === "number" && Number.isFinite(value)
        ? value
        : undefined;
}

function isSeverity(value: unknown): value is Severity {
    return (
        value === Severity.EXPECTED ||
        value === Severity.USER ||
        value === Severity.SYSTEM
    );
}

function readSeverity(
    source: Record<string, unknown>,
    key: string,
): Severity | undefined {
    const value = source[key];

    return isSeverity(value)
        ? value
        : undefined;
}

/**
 * Used when an error response was not generated by the application's normal
 * exception-handling layer, such as a Spring Security 403 response.
 */
function inferSeverity(status: number): Severity {
    if (status >= 400 && status < 500) {
        return Severity.USER;
    }

    return Severity.SYSTEM;
}

function isCsrfState(value: unknown): value is CsrfState {
    if (!isRecord(value)) {
        return false;
    }

    return (
        typeof value.headerName === "string" &&
        value.headerName.length > 0 &&
        typeof value.token === "string" &&
        value.token.length > 0
    );
}

async function requestCsrfToken(): Promise<CsrfState> {
    const response = await fetch("/api/security/csrf", {
        method: "GET",
        credentials: "same-origin",
        headers: {
            Accept: "application/json",
        },
    });

    if (!response.ok) {
        throw new Error(
            `Failed to obtain CSRF token: HTTP ${response.status}`,
        );
    }

    const body: unknown = await response.json();

    if (!isCsrfState(body)) {
        throw new Error(
            "Backend returned an invalid CSRF response",
        );
    }

    csrfState = body;
    return body;
}

async function loadCsrfToken(): Promise<CsrfState> {
    if (csrfState !== null) {
        return csrfState;
    }

    if (csrfLoadPromise === null) {
        csrfLoadPromise = requestCsrfToken()
            .finally(() => {
                csrfLoadPromise = null;
            });
    }

    return csrfLoadPromise;
}

/**
 * Clear the cached token after session expiration, backend restart, logout,
 * or any other operation that rotates the CSRF token.
 */
export function clearCsrfToken(): void {
    csrfState = null;
}

function getRequestMethod(
    input: RequestInfo | URL,
    init: RequestInit,
): string {
    if (init.method) {
        return init.method.toUpperCase();
    }

    if (input instanceof Request) {
        return input.method.toUpperCase();
    }

    return "GET";
}

function createRequestHeaders(
    input: RequestInfo | URL,
    init: RequestInit,
): Headers {
    const headers = new Headers(
        input instanceof Request
            ? input.headers
            : undefined,
    );

    const overrideHeaders = new Headers(init.headers);

    overrideHeaders.forEach((value, name) => {
        headers.set(name, value);
    });

    return headers;
}

export async function apiClient(
    input: RequestInfo | URL,
    init: RequestInit = {},
): Promise<Response> {
    const method = getRequestMethod(input, init);
    const headers = createRequestHeaders(input, init);

    if (!SAFE_METHODS.has(method)) {
        const csrf = await loadCsrfToken();
        headers.set(csrf.headerName, csrf.token);
    }

    return fetch(input, {
        ...init,
        method,
        headers,
        credentials: "same-origin",
    });
}

export async function initializeApiSecurity(): Promise<void> {
    await loadCsrfToken();
}

function getRequestPath(input: RequestInfo | URL): string {
    if (typeof input === "string") {
        return input;
    }

    if (input instanceof URL) {
        return input.toString();
    }

    return input.url;
}

function isJsonContentType(contentType: string): boolean {
    /*
     * Handles:
     * - application/json
     * - application/problem+json
     * - vendor-specific application/*+json
     */
    return contentType.includes("json");
}

async function parseErrorResponse(
    response: Response,
    fallbackPath: string,
): Promise<ErrorResponse> {
    const clonedResponse = response.clone();

    const contentType =
        clonedResponse.headers
            .get("content-type")
            ?.toLowerCase() ?? "";

    let body: unknown;

    try {
        if (isJsonContentType(contentType)) {
            body = await clonedResponse.json();
        } else {
            const text = await clonedResponse.text();

            if (text.trim()) {
                body = {
                    message: text,
                };
            }
        }
    } catch (cause) {
        console.warn(
            "Failed to parse backend error response:",
            cause,
        );
    }

    const record = isRecord(body)
        ? body
        : {};

    const status =
        readNumber(record, "status") ??
        response.status;

    const statusText =
        response.statusText.trim() || undefined;

    return {
        status,

        type:
            readString(record, "type") ??
            readString(record, "error") ??
            statusText ??
            "HttpError",

        message:
            readString(record, "message") ??
            readString(record, "detail") ??
            statusText ??
            `Request failed with HTTP status ${status}`,

        severity:
            readSeverity(record, "severity") ??
            inferSeverity(status),

        path:
            readString(record, "path") ??
            readString(record, "instance") ??
            fallbackPath,
    };
}

function isAbortError(cause: unknown): boolean {
    return (
        cause instanceof DOMException &&
        cause.name === "AbortError"
    );
}

function shouldDisplayGlobally(
    error: ErrorResponse,
    showGlobalError: boolean,
): boolean {
    return (
        showGlobalError &&
        error.severity !== Severity.EXPECTED
    );
}

export async function fetchApi(
    input: RequestInfo | URL,
    init: FetchApiInit = {},
): Promise<Response> {
    const {
        showGlobalError = true,
        ...requestInit
    } = init;

    const normalizedInput = normalizeApiInput(input);
    const path = getRequestPath(normalizedInput);

    let response: Response;

    try {
        response = await apiClient(
            input,
            requestInit,
        );
    } catch (cause) {
        const aborted = isAbortError(cause);

        const errorResponse: ErrorResponse = {
            status: 0,

            type: aborted
                ? "AbortError"
                : "NetworkError",

            severity: aborted
                ? Severity.EXPECTED
                : Severity.SYSTEM,

            message:
                cause instanceof Error
                    ? cause.message
                    : "The backend could not be reached.",

            path,
        };

        logError(
            "Frontend request transport failure: ",
            errorResponse,
        );

        if (shouldDisplayGlobally(
            errorResponse,
            showGlobalError,
        )) {
            setGlobalError(errorResponse);
        }

        throw new ApiRequestError(
            errorResponse,
            undefined,
            { cause },
        );
    }

    if (response.ok) {
        return response;
    }

    const errorResponse = await parseErrorResponse(
        response,
        path,
    );

    logError(
        "Backend request failed: ",
        errorResponse,
    );

    if (shouldDisplayGlobally(
        errorResponse,
        showGlobalError,
    )) {
        setGlobalError(errorResponse);
    }

    throw new ApiRequestError(
        errorResponse,
        response,
    );
}

function ensureApiPath(path: string): string {
    if (path === "/api" || path.startsWith("/api/")) {
        return path;
    }

    if (path === "api" || path.startsWith("api/")) {
        return `/${path}`;
    }

    return `/api/${path.replace(/^\/+/, "")}`;
}

function normalizeApiInput(
    input: RequestInfo | URL,
): RequestInfo | URL {
    if (typeof input === "string") {
        return ensureApiPath(input);
    }

    if (input instanceof URL) {
        const normalizedUrl = new URL(input);
        normalizedUrl.pathname = ensureApiPath(
            normalizedUrl.pathname,
        );

        return normalizedUrl;
    }

    const normalizedUrl = new URL(input.url);
    normalizedUrl.pathname = ensureApiPath(
        normalizedUrl.pathname,
    );

    return new Request(normalizedUrl, input);
}