DROP TABLE IF EXISTS TEST_TABLE CASCADE;
CREATE TABLE TEST_TABLE
(
    first_id    INT          NOT NULL,
    second_id   INT          NOT NULL,
    name        varchar(255) NOT NULL,
    counter     INT          NOT NULL DEFAULT 0,
    description TEXT,
    PRIMARY KEY (first_id, second_id)
);

DROP TABLE IF EXISTS EXTENSION CASCADE;
CREATE TABLE IF NOT EXISTS EXTENSION
(
    id         VARCHAR(255)      NOT NULL PRIMARY KEY,
    config     JSON,
    is_enabled BOOL DEFAULT true NOT NULL
);
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Entry condition tree
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
DROP TABLE IF EXISTS PROLOG_PREDICATE CASCADE;
CREATE TABLE IF NOT EXISTS PROLOG_PREDICATE
(
    id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    name         VARCHAR(128) NOT NULL,
    arity        SMALLINT     NOT NULL DEFAULT 0,

    -- SYSTEM: facts supplied by Java
    -- USER: predicate defined by user-written Prolog clauses
    -- BUILTIN: safe tuProlog predicate exposed in the editor
    kind         VARCHAR(16)  NOT NULL,
    -- Signal to add clauses for type checking at runtime.
    -- Ex.: character/2 character, character transforms into
    -- fears(X, Y):-
    --      character(X), character(Y), fears(X,C), fears(C,Y).
    type_check   BOOLEAN      NOT NULL DEFAULT FALSE,

    -- Used only for SYSTEM predicates.
    -- Maps the predicate to a Java fact provider.
    provider_key VARCHAR(128),

    -- Used only for USER predicates.
    -- May contain one or more Prolog clauses.
    source       TEXT,

    description  TEXT         NOT NULL DEFAULT '',
    enabled      BOOLEAN      NOT NULL DEFAULT TRUE,

    CONSTRAINT uq_prolog_predicate_name_per_arity UNIQUE (name, arity),

    CONSTRAINT chk_prolog_predicate_arity
        CHECK (arity >= 0),

    CONSTRAINT chk_prolog_predicate_kind
        CHECK (kind IN ('SYSTEM', 'USER', 'BUILTIN')),

    CONSTRAINT chk_prolog_predicate_source
        CHECK (
            (kind = 'SYSTEM' AND provider_key IS NOT NULL AND source IS NULL)
                OR
            (kind = 'USER' AND source IS NOT NULL AND provider_key IS NULL)
                OR
            (kind = 'BUILTIN' AND source IS NULL AND provider_key IS NULL)
            )
);

DROP TABLE IF EXISTS PROLOG_PREDICATE_ARGUMENT CASCADE;
CREATE TABLE IF NOT EXISTS PROLOG_PREDICATE_ARGUMENT
(
    predicate_id INT         NOT NULL
        REFERENCES PROLOG_PREDICATE (id)
            ON DELETE CASCADE,

    position     SMALLINT    NOT NULL,
    name         VARCHAR(64) NOT NULL,

    type         VARCHAR(32) NOT NULL,

    CONSTRAINT pk_prolog_predicate_argument PRIMARY KEY (predicate_id, position),

    CONSTRAINT chk_prolog_argument_position
        CHECK (position >= 0),

    CONSTRAINT chk_prolog_argument_type
        CHECK (
            type IN (
                     'CHARACTER',
                     'LOCATION',
                     'WORLD',
                     'REGION',
                     'TAG',
                     'ENTRY',
                     'INTEGER',
                     'NUMBER',
                     'TEXT',
                     'BOOLEAN',
                     'TERM'
                )
            )
);

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
--  Lorebook system
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

DROP TABLE IF EXISTS OUTLET CASCADE;
CREATE TABLE IF NOT EXISTS OUTLET
(
    id     INT          NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    outlet VARCHAR(255) NOT NULL UNIQUE
);

DROP TABLE IF EXISTS LOREBOOKS CASCADE;
CREATE TABLE IF NOT EXISTS LOREBOOKS
(
    id                INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created           TIMESTAMP             DEFAULT CURRENT_TIMESTAMP NOT NULL,
    name              VARCHAR(255) NOT NULL,
    default_outlet_id INT          NOT NULL,
    next_entry_id     INT          NOT NULL DEFAULT 0,

    CONSTRAINT fk_outlet_id FOREIGN KEY (default_outlet_id) REFERENCES OUTLET (id)
);

DROP TABLE IF EXISTS ENTRY CASCADE;
CREATE TABLE IF NOT EXISTS ENTRY
(
    lorebook_id               INT      NOT NULL,
    entry_id                  INT      NOT NULL,
    name                      VARCHAR(255),
    enabled                   bool     NOT NULL DEFAULT TRUE,
    content                   TEXT,

    -- Injection requirements
    probability               smallint NOT NULL default 100,
    outlet                    INT      NOT NULL REFERENCES OUTLET (id),
    delay                     INT      NOT NULL default 0,
    cooldown                  INT      NOT NULL default 0,
    stick_through             INT      NOT NULL default 0,

    -- Injection options
    position                  smallint NOT NULL default 100,
    group_id                  smallint          default null,

    -- Activation strategy
    strategy                  smallint NOT NULL default 0,
    embed_text                TEXT,
    prevent_further_recursion bool     NOT NULL default false,
    non_recursable            bool     NOT NULL default false,
    delay_until_recursion     bool     NOT NULL default false,

    scan_depth                smallint          default null,

    CONSTRAINT chk_valid_position CHECK position >= 0,
    CONSTRAINT uq_entry_name_per_lorebook UNIQUE (name, lorebook_id),
    CONSTRAINT pk_entry PRIMARY KEY (lorebook_id, entry_id),
    CONSTRAINT fk_entry_to_lorebook FOREIGN KEY (lorebook_id) REFERENCES LOREBOOKS (id) ON DELETE CASCADE
);

DROP TABLE IF EXISTS KEYWORD CASCADE;
CREATE TABLE IF NOT EXISTS KEYWORD
(
    id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    keyword  VARCHAR(255) UNIQUE NOT NULL
);

DROP TABLE IF EXISTS ENTRY_KEYWORDS CASCADE;
CREATE TABLE IF NOT EXISTS ENTRY_KEYWORDS
(
    lorebook_id INT NOT NULL REFERENCES LOREBOOKS (id),
    entry_id    INT NOT NULL,
    keyword_id  INT NOT NULL REFERENCES KEYWORD (id),

    CONSTRAINT pk_entry_keywords PRIMARY KEY (lorebook_id, entry_id, keyword_id),
    CONSTRAINT fk_entry_keywords_to_entry FOREIGN KEY (lorebook_id, entry_id) REFERENCES ENTRY (lorebook_id, entry_id) ON DELETE CASCADE
);

DROP TABLE IF EXISTS ENTRY_PROLOG_CONDITION CASCADE;
CREATE TABLE IF NOT EXISTS ENTRY_PROLOG_CONDITION
(
    lorebook_id INT     NOT NULL,
    entry_id    INT     NOT NULL,
    enabled     BOOLEAN NOT NULL DEFAULT TRUE,

    -- A Prolog goal, not a complete Prolog program.
    goal        TEXT    NOT NULL,

    CONSTRAINT pk_entry_prolog_condition PRIMARY KEY (lorebook_id, entry_id),

    CONSTRAINT fk_entry_prolog_condition_to_entry FOREIGN KEY (lorebook_id, entry_id)
        REFERENCES ENTRY (lorebook_id, entry_id)
        ON DELETE CASCADE
);

DROP TABLE IF EXISTS MACROS CASCADE;
CREATE TABLE IF NOT EXISTS MACROS
(
    name               VARCHAR(255)     NOT NULL,
    description        TEXT DEFAULT ' ' NOT NULL,

    constant_value              TEXT DEFAULT NULL,
    macro_provider INT  DEFAULT NULL,

    CONSTRAINT pk_macro_name PRIMARY KEY (name),
    CONSTRAINT fk_macro_to_extension FOREIGN KEY (macro_provider) REFERENCES EXTENSION(id) ON DELETE CASCADE
);

DROP TABLE IF EXISTS REPLACERS CASCADE;
CREATE TABLE IF NOT EXISTS REPLACERS
(
    replace     VARCHAR(255) NOT NULL,
    with_content TEXT,

    macro_provider INT DEFAULT NULL,

    CONSTRAINT pk_replacers PRIMARY KEY (replace)
);

CREATE INDEX IF NOT EXISTS entriesByKeywords ON ENTRY_KEYWORDS (keyword_id);

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- TAGS
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
DROP TABLE IF EXISTS TAGS CASCADE;
CREATE TABLE IF NOT EXISTS TAGS
(
    id    INT                 NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name  VARCHAR(255) UNIQUE NOT NULL,
    color CHAR(7)             NOT NULL DEFAULT '#000000'
);

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Generations
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
DROP TABLE IF EXISTS API_HOSTS CASCADE;
CREATE TABLE IF NOT EXISTS API_HOSTS
(
    id       INT          NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    host_url varchar(255) NOT NULL UNIQUE
);

DROP TABLE IF EXISTS API_KEYS CASCADE;
CREATE TABLE IF NOT EXISTS API_KEYS
(
    name                varchar(255),
    key_id              INT             NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    host_id             INT             NOT NULL REFERENCES API_HOSTS (id),

    api_key_ciphertext  VARBINARY(2048) NOT NULL,
    api_key_nonce       VARBINARY(12)   NOT NULL,
    api_key_key_version INT             NOT NULL DEFAULT 1
);

DROP TABLE IF EXISTS LLM_CONNECTION CASCADE;
CREATE TABLE IF NOT EXISTS LLM_CONNECTION
(
    id         INT                 NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    host_id    smallint REFERENCES API_HOSTS (id),

    name       varchar(255) UNIQUE NOT NULL,

    model      VARCHAR(255)        NOT NULL DEFAULT '',
    max_tokens INT                          DEFAULT 4192,

    CONSTRAINT chk_max_tokens_non_negative CHECK (max_tokens > 0)
);

DROP TABLE IF EXISTS PROMPT_TEMPLATE CASCADE;
CREATE TABLE IF NOT EXISTS PROMPT_TEMPLATE
(
    id                  smallint     NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    connection_id       INT REFERENCES LLM_CONNECTION (id),
    name                VARCHAR(300) NOT NULL UNIQUE,

    --Generation config
    streaming           bool         NOT NULL default false,

    --Gen params
    temperature         float4       NOT NULL DEFAULT 1,
    top_p               float4       NOT NULL default 0.95,
    frequency_penalty   float4       NOT NULL default 0,
    presence_penalty    float4       NOT NULL default 0,
    repetition_penalty  float4       NOT NULL default 0,
    top_k               int          NOT NULL default 0,

    -- Reasoning
    exclude_reasoning   bool         NOT NULL default true,
    reasoning_effort    smallint     NOT NULL,

    -- Prompt budgeting
    max_tokens          INT          NOT NULL DEFAULT 8192,
    lorebooks_budget    FLOAT4       NOT NULL DEFAULT 0.3,
    chat_history_budget FLOAT4       NOT NULL DEFAULT 0.4,

    next_section_id     smallint     NOT NULL default 0,

    CONSTRAINT chk_prompt_template_max_tokens
        CHECK (max_tokens > 0),

    CONSTRAINT chk_prompt_template_temperature
        CHECK (temperature >= 0 AND temperature <= 2),

    CONSTRAINT chk_prompt_template_top_p
        CHECK (top_p >= 0 AND top_p <= 1),

    CONSTRAINT chk_prompt_template_frequency_penalty
        CHECK (frequency_penalty >= -2 AND frequency_penalty <= 2),

    CONSTRAINT chk_prompt_template_presence_penalty
        CHECK (presence_penalty >= -2 AND presence_penalty <= 2),

    CONSTRAINT chk_prompt_template_repetition_penalty
        CHECK (repetition_penalty >= 0 AND repetition_penalty <= 2),

    CONSTRAINT chk_prompt_template_top_k
        CHECK (top_k >= 0),

    CONSTRAINT chk_prompt_template_reasoning_effort
        CHECK (reasoning_effort IS NULL OR reasoning_effort IN (0, 1, 2, 3, 4, 5)),

    CONSTRAINT chk_prompt_template_next_section_id
        CHECK (next_section_id >= 0),

    CONSTRAINT chk_lorebook_budget
        CHECK (lorebooks_budget BETWEEN 0.0 AND 1.0),
    CONSTRAINT chk_history_budget
        CHECK (chat_history_budget BETWEEN 0.0 AND 1.0)
);

DROP TABLE IF EXISTS PROMPT_SECTION CASCADE;
CREATE TABLE IF NOT EXISTS PROMPT_SECTION
(
    prompt_id  smallint     NOT NULL REFERENCES PROMPT_TEMPLATE (id),
    section_id SMALLINT     NOT NULL,
    name       VARCHAR(128) NOT NULL,
    position   SMALLINT     NOT NULL,

    at_depth   int, -- Overrides position and instead renders it at a certain chat depth.

    active     boolean      NOT NULL default true,
    role       VARCHAR(9)   NOT NULL DEFAULT 'user',
    content    TEXT         NOT NULL DEFAULT ' ',

    CONSTRAINT pk_prompt_section PRIMARY KEY (prompt_id, section_id),
    CONSTRAINT chk_unique_name_per_template
        UNIQUE (prompt_id, section_id, name),
    CONSTRAINT chk_unique_position_per_section
        UNIQUE (prompt_id, section_id, position)
);

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
--  Extensions
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
--  Injections
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
DROP TABLE IF EXISTS ENTRY_OUTLET CASCADE;
CREATE TABLE IF NOT EXISTS ENTRY_OUTLET
(
    lorebook_id INT NOT NULL,
    entry_id    INT NOT NULL,
    outlet_id   INT NOT NULL,

    FOREIGN KEY (lorebook_id, entry_id) REFERENCES ENTRY (lorebook_id, entry_id)
);

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
--  World snapshot
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

DROP TABLE IF EXISTS WORLDS CASCADE;
CREATE TABLE IF NOT EXISTS WORLDS
(
    id                          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                        VARCHAR(255) UNIQUE                NOT NULL,
    description                 TEXT             DEFAULT ''        NOT NULL,

    lorebook_id                 INT                                NOT NULL REFERENCES LOREBOOKS (id),

    -- World-space background placement.
    --
    -- All four geometry fields are NULL when no placement is configured.
    -- The WebP itself remains in the asset store.
    background_x                DOUBLE PRECISION,
    background_y                DOUBLE PRECISION,
    background_width            DOUBLE PRECISION,
    background_height           DOUBLE PRECISION,

    -- Background rendering and editing behavior.
    background_opacity          DOUBLE PRECISION DEFAULT 1.0       NOT NULL,
    background_visible          BOOLEAN          DEFAULT TRUE      NOT NULL,
    background_transform_locked BOOLEAN          DEFAULT TRUE      NOT NULL,
    background_aspect_locked    BOOLEAN          DEFAULT TRUE      NOT NULL,
    background_fit              VARCHAR(16)      DEFAULT 'CONTAIN' NOT NULL,

    -- Counters
    next_location_id            INT              DEFAULT 0         NOT NULL,
    next_character_id           INT              DEFAULT 0         NOT NULL,
    next_region_id              INT              DEFAULT 0         NOT NULL,

    CONSTRAINT chk_world_background_geometry
        CHECK (
            (
                background_x IS NULL
                    AND background_y IS NULL
                    AND background_width IS NULL
                    AND background_height IS NULL
                )
                OR
            (
                background_x IS NOT NULL
                    AND background_y IS NOT NULL
                    AND background_width IS NOT NULL
                    AND background_height IS NOT NULL
                    AND background_width > 0
                    AND background_height > 0
                )
            ),

    CONSTRAINT chk_world_background_opacity
        CHECK (background_opacity >= 0.0 AND background_opacity <= 1.0),

    CONSTRAINT chk_world_background_fit CHECK (background_fit IN ('CONTAIN', 'COVER'))
);

-- CREATE TABLE IF NOT EXISTS ARCHETYPE
-- (
--     world_id     INT          NOT NULL,
--     archetype_id INT          NOT NULL,
--
--     name         VARCHAR(255) NOT NULL,
--     description  TEXT,
--     lorebook_id  INT          NOT NULL,
--
--     CONSTRAINT pk_archetype PRIMARY KEY (world_id, archetype_id),
--     CONSTRAINT fk_to_world FOREIGN KEY (world_id) REFERENCES WORLDS (id) ON DELETE CASCADE,
--     CONSTRAINT fk_to_lorebook FOREIGN KEY (lorebook_id) REFERENCES LOREBOOKS (id)
-- );
--


-- CREATE TABLE IF NOT EXISTS CHARACTER_ARCHETYPES
-- (
--     world_id     INT NOT NULL,
--     character_id INT NOT NULL,
--     archetype_id INT NOT NULL,
--
--     CONSTRAINT pk_character_archetypes PRIMARY KEY (world_id, character_id, archetype_id),
--     CONSTRAINT fk_to_world FOREIGN KEY (world_id) references WORLDS (id),
--     CONSTRAINT fk_to_character FOREIGN KEY (world_id, character_id) REFERENCES CHARACTERS (world_id, id),
--     CONSTRAINT fk_to_archetype FOREIGN KEY (world_id, archetype_id) REFERENCES ARCHETYPE (world_id, archetype_id)
-- );
-- CREATE INDEX archetype_by_character_id ON CHARACTER_ARCHETYPES (character_id);

DROP TABLE IF EXISTS REGION CASCADE;
CREATE TABLE IF NOT EXISTS REGION
(
    world_id                 INT              NOT NULL REFERENCES WORLDS (id) ON DELETE CASCADE,
    id                       INT              NOT NULL,

    parent_region_id         INT,

    name                     VARCHAR(255)     NOT NULL,
    description              TEXT             NOT NULL DEFAULT '',
    lorebook_id              INT              NOT NULL REFERENCES LOREBOOKS (id) ON DELETE CASCADE,

    locked                   boolean          NOT NULL DEFAULT FALSE, -- If it can be moved around in the graph
    -- Graph geometry, relative to the parent region.
    x                        DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    y                        DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    width                    DOUBLE PRECISION NOT NULL DEFAULT 100.0,
    height                   DOUBLE PRECISION NOT NULL DEFAULT 100.0,

    -- Region-background rendering behavior.
    background_opacity       DOUBLE PRECISION          DEFAULT 1.0 NOT NULL,
    background_visible       BOOLEAN                   DEFAULT TRUE NOT NULL,
    background_aspect_locked BOOLEAN                   DEFAULT TRUE NOT NULL,
    background_fit           VARCHAR(16)               DEFAULT 'CONTAIN' NOT NULL,

    -- Persist this only if collapse is part of the shared authored layout.
    collapsed                BOOLEAN                   DEFAULT FALSE NOT NULL,

    PRIMARY KEY (world_id, id),

    CONSTRAINT fk_region_parent
        FOREIGN KEY (world_id, parent_region_id)
            REFERENCES REGION (world_id, id)
            ON DELETE SET NULL,

    CONSTRAINT uq_region_name_per_world
        UNIQUE (world_id, name),

    CONSTRAINT chk_region_not_own_parent
        CHECK (
            parent_region_id IS NULL
                OR parent_region_id <> id
            ),

    CONSTRAINT chk_region_positive_size
        CHECK (
            width > 0
                AND height > 0
            ),

    CONSTRAINT chk_region_background_opacity
        CHECK (
            background_opacity >= 0.0
                AND background_opacity <= 1.0
            ),

    CONSTRAINT chk_region_background_fit
        CHECK (
            background_fit IN ('CONTAIN', 'COVER')
            )
);

DROP TABLE IF EXISTS LOCATIONS CASCADE;
CREATE TABLE IF NOT EXISTS LOCATIONS
(
    id          INT              NOT NULL,
    world_id    INT              NOT NULL,

    region_id   INT              NOT NULL,
    name        VARCHAR(255)     NOT NULL,
    description TEXT                      DEFAULT '' NOT NULL,
    lorebook_id INT              NOT NULL REFERENCES LOREBOOKS (id),

    locked      boolean          NOT NULL DEFAULT FALSE, -- If it can be moved around in the graph
    -- Position relative to the containing region.
    x           DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    y           DOUBLE PRECISION NOT NULL DEFAULT 0.0,

    radius      DOUBLE PRECISION          DEFAULT NULL,

    CONSTRAINT pk_locations
        PRIMARY KEY (world_id, id),

    CONSTRAINT uq_location_name_per_region
        UNIQUE (world_id, region_id, name),

    CONSTRAINT fk_location_to_world
        FOREIGN KEY (world_id)
            REFERENCES WORLDS (id)
            ON DELETE CASCADE,

    CONSTRAINT fk_location_to_region
        FOREIGN KEY (world_id, region_id)
            REFERENCES REGION (world_id, id)
            ON DELETE CASCADE
);

DROP TABLE IF EXISTS location_edges CASCADE;
CREATE TABLE IF NOT EXISTS location_edges
(
    world_id                     INT  NOT NULL,
    from_location_id             INT  NOT NULL,
    to_location_id               INT  NOT NULL,

    traversable                  bool NOT NULL DEFAULT TRUE,
    edgeDescription              TEXT,
    show_destination_name        bool NOT NULL DEFAULT TRUE,
    show_destination_description bool NOT NULL DEFAULT FALSE,

    CONSTRAINT pk_location_edges PRIMARY KEY (world_id, from_location_id, to_location_id),
    CONSTRAINT fk_location_edges_worldId FOREIGN KEY (world_id) REFERENCES WORLDS (id) ON DELETE CASCADE,
    CONSTRAINT fk_location_edges_fromLocationId FOREIGN KEY (world_id, from_location_id) REFERENCES LOCATIONS (world_id, id) ON DELETE CASCADE,
    CONSTRAINT fk_location_edges_toLocationId FOREIGN KEY (world_id, to_location_id) REFERENCES LOCATIONS (world_id, id) ON DELETE CASCADE,
    CONSTRAINT chk_duplicates CHECK (from_location_id <> to_location_id) --We disallow self edges
);

DROP TABLE IF EXISTS CHARACTERS CASCADE;
CREATE TABLE IF NOT EXISTS CHARACTERS
(
    -- PK
    world_id             INT                   NOT NULL,
    id                   INT                   NOT NULL,

    -- Lorebook
    lorebook_id          INT                   NOT NULL,

    -- DATA
    name                 VARCHAR(255)          NOT NULL UNIQUE,
    description          TEXT    DEFAULT ''    NOT NULL,
    can_be_user          BOOL    DEFAULT False NOT NULL,
    welcome_message      TEXT    DEFAULT ' '   NOT NULL,

    -- STARTING LOCATION DATA
    starting_location_id INT,
    is_static            BOOLEAN DEFAULT FALSE NOT NULL,
    reason_why           TEXT, --Why the character is there, not the reason why its static
    ttl                  INT     DEFAULT 0,

    CONSTRAINT pk_character PRIMARY KEY (id, world_id),

    CONSTRAINT fk_character_to_world FOREIGN KEY (world_id) REFERENCES WORLDS (id) ON DELETE CASCADE,
    CONSTRAINT fk_character_to_starting_location FOREIGN KEY (starting_location_id, world_id)
        REFERENCES LOCATIONS (id, world_id) ON DELETE SET NULL,
    CONSTRAINT fk_character_to_lorebook FOREIGN KEY (lorebook_id) REFERENCES LOREBOOKS (id),

    CONSTRAINT uk_character_name_per_world UNIQUE (world_id, name)
);
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Entities tags
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- CREATE TABLE IF NOT EXISTS CHARACTER_TAGS
-- (
--     tag_id  INT NOT NULL,
--     char_id INT NOT NULL,
--
--     PRIMARY KEY (tag_id, char_id),
--     FOREIGN KEY (tag_id) REFERENCES TAGS (id) ON DELETE CASCADE,
--     FOREIGN KEY (char_id) REFERENCES CHARACTERS (id) ON DELETE CASCADE
-- );
--
-- CREATE TABLE IF NOT EXISTS LOCATION_TAGS
-- (
--     tag_id      INT NOT NULL,
--     world_id    INT NOT NULL,
--     location_id INT NOT NULL,
--
--     PRIMARY KEY (tag_id, world_id, location_id),
--     FOREIGN KEY (world_id, location_id) REFERENCES LOCATIONS (world_id, id) ON DELETE CASCADE,
--     FOREIGN KEY (tag_id) REFERENCES TAGS (id)
-- );

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- Dynamic payload (actual messages)
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
DROP TABLE IF EXISTS sessions CASCADE;
CREATE TABLE IF NOT EXISTS sessions
(
    id                INT          NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name              VARCHAR(255) NOT NULL,

    world_id          INT          NOT NULL,
    prompt_id         INT,
    user_persona_id   INT          NOT NULL,

    -- Counters
    current_tick      INT          NOT NULL DEFAULT 0,
    next_character_id INT          NOT NULL DEFAULT 0,
    next_location_id  INT          NOT NULL DEFAULT 0,

    CONSTRAINT fk_sessions_to_world FOREIGN KEY (world_id) REFERENCES WORLDS (id) ON DELETE CASCADE,
    CONSTRAINT fk_sessions_to_user_character FOREIGN KEY (world_id, id) REFERENCES CHARACTERS (world_id, id),
    CONSTRAINT fk_sessions_to_template FOREIGN KEY (prompt_id) REFERENCES PROMPT_TEMPLATE (id) ON DELETE SET NULL
);

DROP TABLE IF EXISTS messages CASCADE;
CREATE TABLE IF NOT EXISTS messages
(
    session_id      INT        NOT NULL,
    tick_num        INT        NOT NULL,

    role            varchar(9) NOT NULL,
    request_json    TEXT,
    content         TEXT,
    reasoning       TEXT,

    is_enabled      BOOL       NOT NULL DEFAULT TRUE,
    time            INT        NOT NULL,
    world_id        INT        NOT NULL,           -- Derived
    location_id     INT        NOT NULL,           -- Derived

    active_response SMALLINT   NOT NULL DEFAULT 0, -- ID of the response that's currently active
    response_num    SMALLINT   NOT NULL DEFAULT 0, -- Response num counter to assign keys.

    CONSTRAINT pk_messages PRIMARY KEY (session_id, tick_num),

    CONSTRAINT fk_message_to_session FOREIGN KEY (session_id) REFERENCES sessions (id) ON DELETE CASCADE,
    CONSTRAINT fk_message_to_world FOREIGN KEY (world_id) REFERENCES WORLDS (id) ON DELETE CASCADE,
    CONSTRAINT fk_message_to_location FOREIGN KEY (world_id, location_id) REFERENCES LOCATIONS (world_id, id) ON DELETE CASCADE,

    CONSTRAINT chk_role_is_allowed_value CHECK (role = 'user' OR role = 'assistant'),
    CONSTRAINT request_json_only_for_generated_messages CHECK (request_json IS NULL OR role = 'assistant'),
    CONSTRAINT reasoning_only_for_generated_messages CHECK (reasoning IS NULL OR role = 'assistant'),

    CONSTRAINT chk_active_response_non_negative CHECK active_response >= 0,
    CONSTRAINT chk_response_num_non_negative CHECK response_num >= 0
);

-- CREATE TABLE IF NOT EXISTS extras
-- (
--     session_id   INT  NOT NULL REFERENCES SESSIONS (id) ON DELETE CASCADE,
--     tick_num     INT  NOT NULL,
--     extension_id VARCHAR(255) REFERENCES EXTENSION (id) ON DELETE CASCADE,
--
--     position     int  NOT NULL,
--     content      TEXT NOT NULL,
--
--     CONSTRAINT pk_extras PRIMARY KEY (session_id, tick_num, extension_id),
--     CONSTRAINT fk_extras_message FOREIGN KEY (session_id, tick_num) references MESSAGES (session_id, tick_num) ON DELETE CASCADE
-- );

DROP TABLE IF EXISTS responses CASCADE;
CREATE TABLE IF NOT EXISTS responses
(
    session_id       INT      NOT NULL,
    tick_num         INT      NOT NULL,
    response_num     SMALLINT NOT NULL,

    location_id      INT      NOT NULL,
    world_id         INT      NOT NULL,

    advances_time_by INT      NOT NULL,
    content          TEXT     NOT NULL,
    reasoning        TEXT,

    CONSTRAINT pk_responses PRIMARY KEY (session_id, tick_num, response_num),

    CONSTRAINT fk_to_session FOREIGN KEY (session_id) REFERENCES sessions (id) ON DELETE CASCADE,
    CONSTRAINT fk_responses_messages FOREIGN KEY (session_id, tick_num) REFERENCES messages (session_id, tick_num) ON DELETE CASCADE,

    CONSTRAINT fk_responses_to_world FOREIGN KEY (world_id) REFERENCES WORLDS (id) ON DELETE CASCADE,
    CONSTRAINT fk_responses_locations FOREIGN KEY (world_id, location_id) REFERENCES LOCATIONS (world_id, id),

    CONSTRAINT chck_response_num_valid CHECK (response_num >= 0)
);

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- SESSION STATE
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
DROP TABLE IF EXISTS SESSION_CHARACTERS CASCADE;
CREATE TABLE IF NOT EXISTS SESSION_CHARACTERS
(
    session_id             INT NOT NULL,
    id                     INT NOT NULL,

    permanent_character_id INT          DEFAULT NULL,
    keep_updated           BOOLEAN      DEFAULT FALSE,

    world_id               INT NOT NULL,
    current_location_id    INT NOT NULL,
    last_moved_tick_num    INT NOT NULL DEFAULT 0, --Last time current location was changed.

    session_lorebook_id    INT NOT NULL,

    name                   TEXT         DEFAULT '',
    description            TEXT         DEFAULT '',

    CONSTRAINT pk_session_character PRIMARY KEY (session_id, id),

    CONSTRAINT fk_sesCharacter_to_session FOREIGN KEY (session_id) REFERENCES sessions (id) ON DELETE CASCADE,

    CONSTRAINT fk_sesCharacter_to_world FOREIGN KEY (world_id) REFERENCES WORLDS (id) ON DELETE CASCADE,
    CONSTRAINT fk_sesCharacter_to_location FOREIGN KEY (world_id, current_location_id) REFERENCES
        LOCATIONS (world_id, id) ON DELETE CASCADE,

    CONSTRAINT fk_sesCharacter_to_permanent_character FOREIGN KEY (world_id, permanent_character_id)
        REFERENCES CHARACTERS (world_id, id) ON DELETE SET NULL,
    CONSTRAINT uq_perm_character_per_session
        UNIQUE (session_id, permanent_character_id),

    CONSTRAINT fk_sesCharacter_to_memory_lorebook FOREIGN KEY (session_lorebook_id) REFERENCES LOREBOOKS (id)
);

DROP TABLE IF EXISTS SESSION_LOREBOOK CASCADE;
CREATE TABLE IF NOT EXISTS SESSION_LOREBOOK
(
    session_id  INT NOT NULL,
    lorebook_id INT NOT NULL,

    CONSTRAINT pk_session_lorebook PRIMARY KEY (session_id, lorebook_id),
    CONSTRAINT fk_sesLorebook_to_session FOREIGN KEY (session_id) REFERENCES sessions (id),
    CONSTRAINT fk_sesLorebook_to_lorebook FOREIGN KEY (lorebook_id) REFERENCES LOREBOOKS (id)
);

DROP TABLE IF EXISTS ENTRY_STATE CASCADE;
CREATE TABLE IF NOT EXISTS ENTRY_STATE
(
    session_id          INT NOT NULL,
    lorebook_id         INT NOT NULL,
    entry_id            INT,

    last_activated      INT DEFAULT NULL,
    delay_counter       INT DEFAULT NULL,
    cooldown            INT DEFAULT NULL,
    stay_active_through INT DEFAULT NULL,

    CONSTRAINT pk_entry_state PRIMARY KEY (session_id, lorebook_id, entry_id),
    CONSTRAINT fk_entryState_to_session FOREIGN KEY (session_id) REFERENCES SESSIONS (id),
    CONSTRAINT fk_state_to_entry FOREIGN KEY (lorebook_id, entry_id) REFERENCES ENTRY (lorebook_id, entry_id)
);

-- MOVEMENT HISTORY ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
DROP TABLE IF EXISTS response_location_changes CASCADE;
CREATE TABLE IF NOT EXISTS response_location_changes
(
    session_id           INT      NOT NULL,
    tick_num             INT      NOT NULL,
    response_num         SMALLINT NOT NULL,

    session_character_id INT      NOT NULL,

    -- Location after applying this response
    world_id             INT      NOT NULL,
    location_id          INT      NOT NULL,

    CONSTRAINT pk_response_location_changes PRIMARY KEY (session_id, tick_num, response_num, session_character_id),

    CONSTRAINT fk_response_location_changes_response FOREIGN KEY (session_id, tick_num, response_num)
        REFERENCES RESPONSES (session_id, tick_num, response_num)
        ON DELETE CASCADE,

    CONSTRAINT fk_response_location_changes_location FOREIGN KEY (world_id, location_id)
        REFERENCES locations (world_id, id) ON DELETE CASCADE,

    CONSTRAINT fk_response_locations_to_character FOREIGN KEY (session_id, session_character_id)
        REFERENCES SESSION_CHARACTERS (session_id, id) ON DELETE CASCADE
);

DROP TABLE IF EXISTS MOVEMENTS CASCADE;
CREATE TABLE IF NOT EXISTS MOVEMENTS
(
    session_id           INT NOT NULL REFERENCES SESSIONS (id) ON DELETE CASCADE,
    at_tick              INT NOT NULL, -- When did this character leave this location.

    ses_character_id     INT NOT NULL,

    -- Location before this particular response moved the character.
    world_id             INT NOT NULL REFERENCES WORLDS (id) ON DELETE CASCADE,
    previous_location_id INT NOT NULL,

    CONSTRAINT pk_movements PRIMARY KEY (session_id, at_tick, ses_character_id),

    CONSTRAINT fk_movements_locations FOREIGN KEY (world_id, previous_location_id) references LOCATIONS (world_id, id) ON DELETE CASCADE,
    CONSTRAINT fk_movements_messages FOREIGN KEY (session_id, at_tick) references MESSAGES (session_id, tick_num) ON DELETE CASCADE,
    CONSTRAINT fk_movements_to_characters FOREIGN KEY (session_id, ses_character_id)
        references SESSION_CHARACTERS (session_id, id) ON DELETE CASCADE
);

-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- EXTRA
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
DROP TABLE IF EXISTS TOKENIZER_CACHE CASCADE;
CREATE TABLE IF NOT EXISTS TOKENIZER_CACHE
(
    tokenizer_id        VARCHAR(128) NOT NULL,
    tokenizer_revision  VARCHAR(128) NOT NULL,
    tokenization_mode   VARCHAR(32)  NOT NULL DEFAULT 'RAW_TEXT',

    content_hash        CHAR(64)     NOT NULL,
    content_byte_length INT          NOT NULL,

    token_count         INT          NOT NULL,

    created             TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_used           TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    hit_count           BIGINT       NOT NULL DEFAULT 0,

    CONSTRAINT pk_tokenizer_cache PRIMARY KEY
        (
         tokenizer_id,
         tokenizer_revision,
         tokenization_mode,
         content_hash
            ),

    CONSTRAINT chk_tokenizer_cache_count
        CHECK (token_count >= 0),

    CONSTRAINT chk_tokenizer_cache_byte_length
        CHECK (content_byte_length >= 0)
);

CREATE INDEX IF NOT EXISTS tokenizer_cache_last_used
    ON TOKENIZER_CACHE (last_used);