DROP TABLE IF EXISTS TEST_TABLE CASCADE;
CREATE TABLE TEST_TABLE
(
    first_id  INT NOT NULL,
    second_id INT NOT NULL,
    name varchar(255) NOT NULL,
    counter INT NOT NULL DEFAULT 0,
    description TEXT,
    PRIMARY KEY (first_id, second_id)
);

DROP TABLE IF EXISTS OUTLET CASCADE;
CREATE TABLE OUTLET
(
    id     INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    outlet VARCHAR(255) NOT NULL UNIQUE
);

DROP TABLE IF EXISTS LOREBOOKS CASCADE;
CREATE TABLE LOREBOOKS
(
    id                INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created           TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    name              VARCHAR(255) NOT NULL,
    default_outlet_id INT REFERENCES OUTLET (id),
    next_entry_id     INT NOT NULL DEFAULT 0
);

DROP TABLE IF EXISTS ENTRY CASCADE;
CREATE TABLE ENTRY
(
    lorebook_id               INT NOT NULL,
    entry_id                  INT NOT NULL,
    name                      VARCHAR(255),
    enabled                   bool NOT NULL DEFAULT TRUE,
    content                   TEXT,
    probability               smallint default 100,
    is_custom_outlet          BOOL NOT NULL DEFAULT FALSE,
    outlet                    INT REFERENCES OUTLET (id),
    delay                     INT NOT NULL default 0,
    cooldown                  INT NOT NULL default 0,
    stick_through             INT NOT NULL default 0,
    injection_order           smallint default 100,
    strategy                  smallint default 0,
    embed_text                TEXT,
    prevent_further_recursion bool NOT NULL default false,
    non_recursable            bool NOT NULL default false,
    delay_until_recursion     bool NOT NULL default false,
    scan_depth                smallint default null,

    PRIMARY KEY (lorebook_id, entry_id),
    FOREIGN KEY (lorebook_id) REFERENCES LOREBOOKS (id) ON DELETE CASCADE
);

DROP TABLE IF EXISTS KEYWORD CASCADE;
CREATE TABLE KEYWORD
(
    id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    is_regex BOOL NOT NULL DEFAULT FALSE,
    keyword  VARCHAR(255) UNIQUE NOT NULL
);

DROP TABLE IF EXISTS ENTRY_KEYWORDS CASCADE;
CREATE TABLE ENTRY_KEYWORDS
(
    lorebook_id INT NOT NULL,
    entry_id    INT NOT NULL,
    keyword_id  INT NOT NULL,

    PRIMARY KEY (lorebook_id, entry_id, keyword_id),
    FOREIGN KEY (lorebook_id, entry_id) REFERENCES ENTRY (lorebook_id, entry_id) ON DELETE CASCADE,
    FOREIGN KEY (keyword_id) REFERENCES KEYWORD (id)
);

DROP INDEX IF EXISTS entriesByKeywords;
CREATE INDEX entriesByKeywords ON ENTRY_KEYWORDS (keyword_id);

DROP TABLE IF EXISTS TAGS CASCADE;
CREATE TABLE TAGS
(
    id    INT NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name  VARCHAR(255) UNIQUE NOT NULL,
    color CHAR(7) NOT NULL DEFAULT '#000000'
);

DROP TABLE IF EXISTS API_HOSTS CASCADE;
CREATE TABLE API_HOSTS
(
    id       INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    host_url varchar(255) NOT NULL UNIQUE
);

DROP TABLE IF EXISTS API_KEYS CASCADE;
CREATE TABLE API_KEYS
(
    name                varchar(255),
    key_id              INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    host_id             INT NOT NULL REFERENCES API_HOSTS (id),
    api_key_ciphertext  VARBINARY(2048) NOT NULL,
    api_key_nonce       VARBINARY(12) NOT NULL,
    api_key_key_version INT NOT NULL DEFAULT 1
);

DROP TABLE IF EXISTS LLM_CONNECTION CASCADE;
CREATE TABLE LLM_CONNECTION
(
    id      INT                 NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    host_id smallint            REFERENCES API_HOSTS (id),

    name    varchar(255) UNIQUE NOT NULL,

    model      VARCHAR(255)        NOT NULL DEFAULT '',
    max_tokens INT
);
DROP TABLE IF EXISTS PROMPT_TEMPLATE CASCADE;
CREATE TABLE PROMPT_TEMPLATE
(
    id                 smallint NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    connection_id      smallint REFERENCES LLM_CONNECTION (id),
    name               VARCHAR(300) NOT NULL UNIQUE,
    max_tokens         INT NOT NULL DEFAULT 8192,
    streaming          bool NOT NULL default false,
    temperature        float4 NOT NULL DEFAULT 1,
    top_p              float4 NOT NULL default 0.95,
    frequency_penalty  float4 NOT NULL default 0,
    presence_penalty   float4 NOT NULL default 0,
    repetition_penalty float4 NOT NULL default 0,
    top_k              int NOT NULL default 0,
    exclude_reasoning  bool NOT NULL default true,
    reasoning_effort   smallint NOT NULL,
    next_section_id    smallint NOT NULL default 0,

    CONSTRAINT chk_prompt_template_max_tokens CHECK (max_tokens > 0),
    CONSTRAINT chk_prompt_template_temperature CHECK (temperature >= 0 AND temperature <= 2),
    CONSTRAINT chk_prompt_template_top_p CHECK (top_p >= 0 AND top_p <= 1),
    CONSTRAINT chk_prompt_template_frequency_penalty CHECK (frequency_penalty >= -2 AND frequency_penalty <= 2),
    CONSTRAINT chk_prompt_template_presence_penalty CHECK (presence_penalty >= -2 AND presence_penalty <= 2),
    CONSTRAINT chk_prompt_template_repetition_penalty CHECK (repetition_penalty >= 0 AND repetition_penalty <= 2),
    CONSTRAINT chk_prompt_template_top_k CHECK (top_k >= 0),
    CONSTRAINT chk_prompt_template_reasoning_effort CHECK (reasoning_effort IS NULL OR reasoning_effort IN (0, 1, 2, 3, 4, 5)),
    CONSTRAINT chk_prompt_template_next_section_id CHECK (next_section_id >= 0)
);

DROP TABLE IF EXISTS PROMPT_SECTION CASCADE;
CREATE TABLE PROMPT_SECTION
(
    prompt_id  smallint NOT NULL REFERENCES PROMPT_TEMPLATE (id),
    section_id SMALLINT NOT NULL,
    name       VARCHAR(128) NOT NULL UNIQUE,
    position   SMALLINT NOT NULL UNIQUE,
    active     boolean NOT NULL default true,
    role       VARCHAR(9) NOT NULL DEFAULT 'user',
    content    TEXT NOT NULL DEFAULT ''
);

DROP TABLE IF EXISTS EXTENSION CASCADE;
CREATE TABLE EXTENSION
(
    id     VARCHAR(255) NOT NULL PRIMARY KEY,
    config JSON
);

DROP TABLE IF EXISTS ENTRY_OUTLET CASCADE;
CREATE TABLE ENTRY_OUTLET
(
    lorebook_id INT NOT NULL,
    entry_id    INT NOT NULL,
    outlet_id   INT NOT NULL,

    FOREIGN KEY (lorebook_id, entry_id) REFERENCES ENTRY (lorebook_id, entry_id)
);

DROP TABLE IF EXISTS CHARACTERS CASCADE;
CREATE TABLE CHARACTERS
(
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    created         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    name            VARCHAR(255) NOT NULL UNIQUE,
    is_archetype    BOOL DEFAULT False NOT NULL,
    can_be_user     BOOL DEFAULT False NOT NULL,
    welcome_message TEXT DEFAULT ' ' NOT NULL,
    lorebook_id     INT NOT NULL REFERENCES LOREBOOKS (id)
);

DROP TABLE IF EXISTS WORLDS CASCADE;
CREATE TABLE WORLDS
(
    id               INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             VARCHAR(255) NOT NULL UNIQUE,
    next_location_id INT NOT NULL DEFAULT 0,
    lorebook_id      INT NOT NULL,
    FOREIGN KEY (lorebook_id) REFERENCES LOREBOOKS (id)
);

DROP TABLE IF EXISTS LOCATIONS CASCADE;
CREATE TABLE LOCATIONS
(
    id          INT NOT NULL,
    world_id    INT NOT NULL,
    name        VARCHAR(255) NOT NULL,
    lorebook_id INT NOT NULL REFERENCES LOREBOOKS (id),

    PRIMARY KEY (world_id, id),
    FOREIGN KEY (world_id) REFERENCES WORLDS (id) ON DELETE CASCADE,
    UNIQUE (world_id, name)
);

DROP TABLE IF EXISTS starting_locations CASCADE;
CREATE TABLE starting_locations
(
    character_id INT NOT NULL,
    world_id     INT NOT NULL,
    location_id  INT NOT NULL,
    is_static    BOOLEAN NOT NULL DEFAULT FALSE,
    reason_why   TEXT,
    ttl          INT DEFAULT 0,

    PRIMARY KEY (character_id, world_id),
    FOREIGN KEY (character_id) REFERENCES characters (id) ON DELETE CASCADE,
    FOREIGN KEY (world_id, location_id) REFERENCES LOCATIONS (world_id, id) ON DELETE CASCADE,
    FOREIGN KEY (world_id) REFERENCES WORLDS (id) ON DELETE CASCADE
);

DROP TABLE IF EXISTS location_neighbors CASCADE;
CREATE TABLE location_neighbors
(
    world_id        INT NOT NULL,
    location1_id    INT NOT NULL,
    location2_id    INT NOT NULL,
    travelCost      INT NOT NULL DEFAULT 0,
    edgeDescription TEXT,

    PRIMARY KEY (world_id, location1_id, location2_id),
    FOREIGN KEY (world_id, location1_id) REFERENCES LOCATIONS (world_id, id) ON DELETE CASCADE,
    FOREIGN KEY (world_id, location2_id) REFERENCES LOCATIONS (world_id, id) ON DELETE CASCADE,
    CONSTRAINT chk_duplicates CHECK (location1_id <> location2_id)
);

DROP TABLE IF EXISTS CHARACTER_TAGS CASCADE;
CREATE TABLE CHARACTER_TAGS
(
    tag_id  INT NOT NULL,
    char_id INT NOT NULL,

    PRIMARY KEY (tag_id, char_id),
    FOREIGN KEY (tag_id) REFERENCES TAGS (id) ON DELETE CASCADE,
    FOREIGN KEY (char_id) REFERENCES CHARACTERS (id) ON DELETE CASCADE
);

DROP TABLE IF EXISTS LOCATION_TAGS CASCADE;
CREATE TABLE LOCATION_TAGS
(
    tag_id      INT NOT NULL,
    world_id    INT NOT NULL,
    location_id INT NOT NULL,

    PRIMARY KEY (tag_id, world_id, location_id),
    FOREIGN KEY (world_id, location_id) REFERENCES LOCATIONS (world_id, id) ON DELETE CASCADE,
    FOREIGN KEY (tag_id) REFERENCES TAGS (id)
);

DROP TABLE IF EXISTS sessions CASCADE;
CREATE TABLE sessions
(
    id              INT NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255) NOT NULL,
    world_id        INT NOT NULL REFERENCES WORLDS (id) ON DELETE CASCADE,
    main_prompt     INT REFERENCES PROMPT_TEMPLATE (id),
    user_persona_id INT NOT NULL REFERENCES CHARACTERS (id) ON DELETE CASCADE,
    current_tick    INT NOT NULL DEFAULT 0
);

DROP TABLE IF EXISTS messages CASCADE;
CREATE TABLE messages
(
    session_id      INT        NOT NULL REFERENCES SESSIONS (id) ON DELETE CASCADE,
    tick_num        INT        NOT NULL,

    role            varchar(9) NOT NULL CHECK (role = 'user' OR role = 'assistant'),
    request_json    TEXT,                          -- Stored, but it could also just be regen. Should only be there for assistant msgs
    content         TEXT,                          -- Always derived

    time            INT        NOT NULL,
    world_id        INT        NOT NULL REFERENCES WORLDS (id), -- Derived
    location_id     INT        NOT NULL, -- Derived

    active_response SMALLINT   NOT NULL DEFAULT 0, -- ID of the response that's currently active
    response_num    SMALLINT   NOT NULL DEFAULT 0, -- Response num counter to assign keys.

    PRIMARY KEY (session_id, tick_num),
    FOREIGN KEY (location_id, world_id) REFERENCES LOCATIONS (id, world_id),
    CONSTRAINT request_json_only_for_generated_messages CHECK (request_json IS NULL OR role = 'assistant')
);

DROP TABLE IF EXISTS extras CASCADE;
CREATE TABLE extras
(
    session_id   INT NOT NULL REFERENCES SESSIONS (id) ON DELETE CASCADE,
    tick_num     INT NOT NULL,
    extension_id VARCHAR(255) REFERENCES EXTENSION (id),

    position     int NOT NULL,
    content      TEXT NOT NULL,

    PRIMARY KEY (session_id, tick_num, extension_id),
    FOREIGN KEY (session_id, tick_num) references MESSAGES (session_id, tick_num)
);

DROP TABLE IF EXISTS responses CASCADE;
CREATE TABLE IF NOT EXISTS responses
(
    session_id       INT      NOT NULL REFERENCES SESSIONS (id) ON DELETE CASCADE,
    tick_num         INT      NOT NULL,
    response_num     SMALLINT NOT NULL,

    location_id      INT      NOT NULL,
    world_id         INT      NOT NULL REFERENCES WORLDS (id),

    advances_time_by INT      NOT NULL,
    content          TEXT     NOT NULL,

    PRIMARY KEY (session_id, tick_num, response_num),
    FOREIGN KEY (location_id, world_id) REFERENCES LOCATIONS (id, world_id) ON DELETE CASCADE,

    FOREIGN KEY (session_id, tick_num)
        REFERENCES messages (session_id, tick_num)
        ON DELETE CASCADE
);

DROP TABLE IF EXISTS response_location_changes;
CREATE TABLE IF NOT EXISTS response_location_changes
(
    session_id   INT      NOT NULL,
    tick_num     INT      NOT NULL,
    response_num SMALLINT NOT NULL,

    character_id INT      NOT NULL REFERENCES characters (id),

    -- Location after applying this response
    world_id     INT      NOT NULL,
    location_id  INT      NOT NULL,

    PRIMARY KEY (
                 session_id,
                 tick_num,
                 response_num,
                 character_id
        ),

    FOREIGN KEY (
                 session_id,
                 tick_num,
                 response_num
        )
        REFERENCES responses (
                              session_id,
                              tick_num,
                              response_num
            )
        ON DELETE CASCADE,

    FOREIGN KEY (location_id, world_id)
        REFERENCES locations (id, world_id)
);

DROP TABLE IF EXISTS MOVEMENTS CASCADE;
CREATE TABLE MOVEMENTS
(
    session_id   INT NOT NULL REFERENCES SESSIONS (id) ON DELETE CASCADE,
    at_tick      INT NOT NULL,

    character_id INT NOT NULL REFERENCES CHARACTERS (id),

    -- Location before this particular response moved the character.
    world_id     INT NOT NULL REFERENCES WORLDS (id),
    previous_location_id  INT NOT NULL,

    PRIMARY KEY (session_id, at_tick, character_id),
    FOREIGN KEY (previous_location_id, world_id) references LOCATIONS (id, world_id),
    FOREIGN KEY (session_id, at_tick) references MESSAGES (session_id, tick_num) ON DELETE CASCADE
);

DROP TABLE IF EXISTS CURRENT_LOCATIONS CASCADE;
CREATE TABLE CURRENT_LOCATIONS
(
    session_id   INT NOT NULL REFERENCES SESSIONS (id) ON DELETE CASCADE,
    tick_num     INT NOT NULL,                            -- When did this guy reach this location? (In message tick). Isn't necessarily the last message tick.

    character_id INT NOT NULL REFERENCES CHARACTERS (id), -- who

    world_id     INT NOT NULL REFERENCES WORLDS (id),     -- where
    location_id  INT NOT NULL,

    PRIMARY KEY (session_id, character_id),
    FOREIGN KEY (location_id, world_id) REFERENCES LOCATIONS (id, world_id),
    FOREIGN KEY (session_id, tick_num) REFERENCES MESSAGES (session_id, tick_num) ON DELETE CASCADE
);